apiVersion: kubescheduler.config.k8s.io/v1beta13
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "/etc/kubernetes/scheduler.conf"
profiles:
  - schedulerName: energy-aware-scheduler
    plugins:
      score:
        enabled:
          - name: EnergyAware
    pluginConfig:
      - name: EnergyAware
        args:
          prometheusAddress: "http://localhost:9090"
          networkInterface: "wlan0"
          timeRangeInMinutes: 1
